steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vscode-server-cloudrun:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vscode-server-cloudrun:latest'
      - '.'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vscode-server-cloudrun:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'vscode-server-cloudrun'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vscode-server-cloudrun:latest'
      - '--region'
      - 'europe-west4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--cpu'
      - '1'
      - '--memory'
      - '2Gi'
      - '--max-instances'
      - '1'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '3600'
      - '--set-env-vars'
      - 'CODE_SERVER_PASSWORD=P@ssw0rd@123'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/vscode-server-cloudrun:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/vscode-server-cloudrun:latest'

# Set timeout
timeout: '1200s'