name: Terraform Validate

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'gcp/**'
      - 'oci/**'
      - '.github/workflows/**'
  push:
    branches:
      - main
      - master
    paths:
      - 'gcp/**'
      - 'oci/**'

env:
  TF_VERSION: '1.6.0'

jobs:
  validate-gcp:
    name: 'Validate GCP Terraform'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Terraform Format Check
        working-directory: ./gcp
        run: terraform fmt -check -recursive
        continue-on-error: true
      
      - name: Terraform Init
        working-directory: ./gcp
        run: terraform init -backend=false
      
      - name: Terraform Validate
        working-directory: ./gcp
        run: terraform validate

  validate-oci:
    name: 'Validate OCI Terraform'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Terraform Format Check
        working-directory: ./oci
        run: terraform fmt -check -recursive
        continue-on-error: true
      
      - name: Terraform Init
        working-directory: ./oci
        run: terraform init -backend=false
      
      - name: Terraform Validate
        working-directory: ./oci
        run: terraform validate

  security-scan:
    name: 'Security Scan'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
